# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('createDatetime', models.DateTimeField(auto_now_add=True)),
                ('directory', models.FilePathField(match='*.yml', max_length=200, path='D:\\web\\depot\\roles', recursive=True)),
                ('tasks', models.FileField(upload_to=upload.models.task_dir)),
                ('vars', models.FileField(upload_to=upload.models.var_dir)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
