# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depotapp', '0003_auto_20170106_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='depotapp.Order'),
            preserve_default=False,
        ),
    ]
