# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depotapp', '0004_auto_20170108_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(through='depotapp.LineItem', to='depotapp.Order'),
        ),
    ]
